// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2U2b8gf-jIpT1YsLUDEu1VhoJJoDCOXI',
    appId: '1:974147493782:web:3652333513e4025df687b7',
    messagingSenderId: '974147493782',
    projectId: 'signinsignup-99852',
    authDomain: 'signinsignup-99852.firebaseapp.com',
    storageBucket: 'signinsignup-99852.appspot.com',
    measurementId: 'G-9NFXLR68C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClH8i2-ivWjhKlF-6_VXk8nfWEwiFgQSA',
    appId: '1:974147493782:android:ca34f0834b2ce622f687b7',
    messagingSenderId: '974147493782',
    projectId: 'signinsignup-99852',
    storageBucket: 'signinsignup-99852.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAArbrG6xGPkJDNCHCM59oiJpWkJVZ6ksA',
    appId: '1:974147493782:ios:11f9e5178e16fe19f687b7',
    messagingSenderId: '974147493782',
    projectId: 'signinsignup-99852',
    storageBucket: 'signinsignup-99852.appspot.com',
    iosClientId: '974147493782-ensk0m58d109e8m0k5civ6qhml33hlg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinsignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAArbrG6xGPkJDNCHCM59oiJpWkJVZ6ksA',
    appId: '1:974147493782:ios:11f9e5178e16fe19f687b7',
    messagingSenderId: '974147493782',
    projectId: 'signinsignup-99852',
    storageBucket: 'signinsignup-99852.appspot.com',
    iosClientId: '974147493782-ensk0m58d109e8m0k5civ6qhml33hlg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinsignup',
  );
}
